/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n serialFIFO -lang verilog -synth lse -bus_exp 7 -bb -arch xo2c00 -type ebfifo -depth 64 -width 8 -rwidth 8 -pfu_fifo -no_enable -pe 8 -pf 56  */
/* Sun Sep 11 17:37:26 2022 */


`timescale 1 ns / 1 ps
module serialFIFO (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, Q, 
    Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [7:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [7:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire invout_1;
    wire invout_0;
    wire wptr_5_inv;
    wire wptr_4_inv;
    wire w_gdata_0;
    wire w_gdata_1;
    wire w_gdata_2;
    wire w_gdata_3;
    wire w_gdata_4;
    wire w_gdata_5;
    wire wptr_4;
    wire wptr_5;
    wire wptr_6;
    wire r_gdata_0;
    wire r_gdata_1;
    wire r_gdata_2;
    wire r_gdata_3;
    wire r_gdata_4;
    wire r_gdata_5;
    wire rptr_6;
    wire w_gcount_0;
    wire w_gcount_1;
    wire w_gcount_2;
    wire w_gcount_3;
    wire w_gcount_4;
    wire w_gcount_5;
    wire w_gcount_6;
    wire r_gcount_0;
    wire r_gcount_1;
    wire r_gcount_2;
    wire r_gcount_3;
    wire r_gcount_4;
    wire r_gcount_5;
    wire r_gcount_6;
    wire w_gcount_r20;
    wire w_gcount_r0;
    wire w_gcount_r21;
    wire w_gcount_r1;
    wire w_gcount_r22;
    wire w_gcount_r2;
    wire w_gcount_r23;
    wire w_gcount_r3;
    wire w_gcount_r24;
    wire w_gcount_r4;
    wire w_gcount_r25;
    wire w_gcount_r5;
    wire w_gcount_r26;
    wire w_gcount_r6;
    wire r_gcount_w20;
    wire r_gcount_w0;
    wire r_gcount_w21;
    wire r_gcount_w1;
    wire r_gcount_w22;
    wire r_gcount_w2;
    wire r_gcount_w23;
    wire r_gcount_w3;
    wire r_gcount_w24;
    wire r_gcount_w4;
    wire r_gcount_w25;
    wire r_gcount_w5;
    wire r_gcount_w26;
    wire r_gcount_w6;
    wire empty_i;
    wire full_i;
    wire rRst;
    wire iwcount_0;
    wire iwcount_1;
    wire w_gctr_ci;
    wire iwcount_2;
    wire iwcount_3;
    wire co0;
    wire iwcount_4;
    wire iwcount_5;
    wire co1;
    wire iwcount_6;
    wire co3;
    wire co2;
    wire wcount_6;
    wire ircount_0;
    wire ircount_1;
    wire r_gctr_ci;
    wire ircount_2;
    wire ircount_3;
    wire co0_1;
    wire ircount_4;
    wire ircount_5;
    wire co1_1;
    wire ircount_6;
    wire co3_1;
    wire co2_1;
    wire rcount_6;
    wire rdataout7;
    wire rdataout6;
    wire rdataout5;
    wire rdataout4;
    wire rdataout3;
    wire rdataout2;
    wire rdataout1;
    wire rdataout0;
    wire rptr_5;
    wire rptr_4;
    wire cmp_ci;
    wire rcount_0;
    wire rcount_1;
    wire co0_2;
    wire rcount_2;
    wire rcount_3;
    wire co1_2;
    wire rcount_4;
    wire rcount_5;
    wire co2_2;
    wire empty_cmp_clr;
    wire empty_cmp_set;
    wire empty_d;
    wire empty_d_c;
    wire cmp_ci_1;
    wire wcount_0;
    wire wcount_1;
    wire co0_3;
    wire wcount_2;
    wire wcount_3;
    wire co1_3;
    wire wcount_4;
    wire wcount_5;
    wire co2_3;
    wire full_cmp_clr;
    wire full_cmp_set;
    wire full_d;
    wire full_d_c;
    wire iae_setcount_0;
    wire iae_setcount_1;
    wire ae_set_ctr_ci;
    wire iae_setcount_2;
    wire iae_setcount_3;
    wire co0_4;
    wire iae_setcount_4;
    wire iae_setcount_5;
    wire co1_4;
    wire iae_setcount_6;
    wire co3_2;
    wire co2_4;
    wire ae_setcount_6;
    wire rden_i;
    wire cmp_ci_2;
    wire wcount_r0;
    wire wcount_r1;
    wire ae_setcount_0;
    wire ae_setcount_1;
    wire co0_5;
    wire wcount_r2;
    wire w_g2b_xor_cluster_0;
    wire ae_setcount_2;
    wire ae_setcount_3;
    wire co1_5;
    wire wcount_r4;
    wire wcount_r5;
    wire ae_setcount_4;
    wire ae_setcount_5;
    wire co2_5;
    wire ae_set_cmp_clr;
    wire ae_set_cmp_set;
    wire ae_set_d;
    wire ae_set_d_c;
    wire scuba_vhi;
    wire iaf_setcount_0;
    wire iaf_setcount_1;
    wire af_set_ctr_ci;
    wire iaf_setcount_2;
    wire iaf_setcount_3;
    wire co0_6;
    wire iaf_setcount_4;
    wire iaf_setcount_5;
    wire co1_6;
    wire iaf_setcount_6;
    wire co3_3;
    wire co2_6;
    wire af_setcount_6;
    wire wren_i;
    wire cmp_ci_3;
    wire rcount_w0;
    wire rcount_w1;
    wire af_setcount_0;
    wire af_setcount_1;
    wire co0_7;
    wire rcount_w2;
    wire r_g2b_xor_cluster_0;
    wire af_setcount_2;
    wire af_setcount_3;
    wire co1_7;
    wire rcount_w4;
    wire rcount_w5;
    wire af_setcount_4;
    wire af_setcount_5;
    wire co2_7;
    wire af_set_cmp_clr;
    wire af_set_cmp_set;
    wire af_set;
    wire af_set_c;
    wire scuba_vlo;
    wire mdL0_0_7;
    wire mdL0_0_6;
    wire mdL0_0_5;
    wire mdL0_0_4;
    wire mdL0_0_3;
    wire mdL0_0_2;
    wire mdL0_0_1;
    wire mdL0_0_0;
    wire dec0_wre3;
    wire mdL0_1_7;
    wire mdL0_1_6;
    wire mdL0_1_5;
    wire mdL0_1_4;
    wire mdL0_1_3;
    wire mdL0_1_2;
    wire mdL0_1_1;
    wire mdL0_1_0;
    wire dec1_wre7;
    wire mdL0_2_7;
    wire mdL0_2_6;
    wire mdL0_2_5;
    wire mdL0_2_4;
    wire mdL0_2_3;
    wire mdL0_2_2;
    wire mdL0_2_1;
    wire mdL0_2_0;
    wire dec2_wre11;
    wire mdL0_3_7;
    wire mdL0_3_6;
    wire mdL0_3_5;
    wire mdL0_3_4;
    wire mdL0_3_3;
    wire mdL0_3_2;
    wire mdL0_3_1;
    wire mdL0_3_0;
    wire rptr_3;
    wire rptr_2;
    wire rptr_1;
    wire rptr_0;
    wire dec3_wre15;
    wire wptr_3;
    wire wptr_2;
    wire wptr_1;
    wire wptr_0;

    AND2 AND2_t14 (.A(WrEn), .B(invout_1), .Z(wren_i));

    INV INV_3 (.A(full_i), .Z(invout_1));

    AND2 AND2_t13 (.A(RdEn), .B(invout_0), .Z(rden_i));

    INV INV_2 (.A(empty_i), .Z(invout_0));

    OR2 OR2_t12 (.A(Reset), .B(RPReset), .Z(rRst));

    XOR2 XOR2_t11 (.A(wcount_0), .B(wcount_1), .Z(w_gdata_0));

    XOR2 XOR2_t10 (.A(wcount_1), .B(wcount_2), .Z(w_gdata_1));

    XOR2 XOR2_t9 (.A(wcount_2), .B(wcount_3), .Z(w_gdata_2));

    XOR2 XOR2_t8 (.A(wcount_3), .B(wcount_4), .Z(w_gdata_3));

    XOR2 XOR2_t7 (.A(wcount_4), .B(wcount_5), .Z(w_gdata_4));

    XOR2 XOR2_t6 (.A(wcount_5), .B(wcount_6), .Z(w_gdata_5));

    XOR2 XOR2_t5 (.A(rcount_0), .B(rcount_1), .Z(r_gdata_0));

    XOR2 XOR2_t4 (.A(rcount_1), .B(rcount_2), .Z(r_gdata_1));

    XOR2 XOR2_t3 (.A(rcount_2), .B(rcount_3), .Z(r_gdata_2));

    XOR2 XOR2_t2 (.A(rcount_3), .B(rcount_4), .Z(r_gdata_3));

    XOR2 XOR2_t1 (.A(rcount_4), .B(rcount_5), .Z(r_gdata_4));

    XOR2 XOR2_t0 (.A(rcount_5), .B(rcount_6), .Z(r_gdata_5));

    INV INV_1 (.A(wptr_4), .Z(wptr_4_inv));

    INV INV_0 (.A(wptr_5), .Z(wptr_5_inv));

    defparam LUT4_23.initval =  16'h8000 ;
    ROM16X1A LUT4_23 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(wptr_4_inv), .AD0(wptr_5_inv), 
        .DO0(dec0_wre3));

    defparam LUT4_22.initval =  16'h8000 ;
    ROM16X1A LUT4_22 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(wptr_4), .AD0(wptr_5_inv), 
        .DO0(dec1_wre7));

    defparam LUT4_21.initval =  16'h8000 ;
    ROM16X1A LUT4_21 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(wptr_4_inv), .AD0(wptr_5), 
        .DO0(dec2_wre11));

    defparam LUT4_20.initval =  16'h8000 ;
    ROM16X1A LUT4_20 (.AD3(scuba_vhi), .AD2(wren_i), .AD1(wptr_4), .AD0(wptr_5), 
        .DO0(dec3_wre15));

    defparam LUT4_19.initval =  16'h6996 ;
    ROM16X1A LUT4_19 (.AD3(w_gcount_r23), .AD2(w_gcount_r24), .AD1(w_gcount_r25), 
        .AD0(w_gcount_r26), .DO0(w_g2b_xor_cluster_0));

    defparam LUT4_18.initval =  16'h6996 ;
    ROM16X1A LUT4_18 (.AD3(w_gcount_r25), .AD2(w_gcount_r26), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(wcount_r5));

    defparam LUT4_17.initval =  16'h6996 ;
    ROM16X1A LUT4_17 (.AD3(w_gcount_r24), .AD2(w_gcount_r25), .AD1(w_gcount_r26), 
        .AD0(scuba_vlo), .DO0(wcount_r4));

    defparam LUT4_16.initval =  16'h6996 ;
    ROM16X1A LUT4_16 (.AD3(w_gcount_r22), .AD2(w_gcount_r23), .AD1(w_gcount_r24), 
        .AD0(wcount_r5), .DO0(wcount_r2));

    defparam LUT4_15.initval =  16'h6996 ;
    ROM16X1A LUT4_15 (.AD3(w_gcount_r21), .AD2(w_gcount_r22), .AD1(w_gcount_r23), 
        .AD0(wcount_r4), .DO0(wcount_r1));

    defparam LUT4_14.initval =  16'h6996 ;
    ROM16X1A LUT4_14 (.AD3(w_gcount_r20), .AD2(w_gcount_r21), .AD1(w_gcount_r22), 
        .AD0(w_g2b_xor_cluster_0), .DO0(wcount_r0));

    defparam LUT4_13.initval =  16'h6996 ;
    ROM16X1A LUT4_13 (.AD3(r_gcount_w23), .AD2(r_gcount_w24), .AD1(r_gcount_w25), 
        .AD0(r_gcount_w26), .DO0(r_g2b_xor_cluster_0));

    defparam LUT4_12.initval =  16'h6996 ;
    ROM16X1A LUT4_12 (.AD3(r_gcount_w25), .AD2(r_gcount_w26), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(rcount_w5));

    defparam LUT4_11.initval =  16'h6996 ;
    ROM16X1A LUT4_11 (.AD3(r_gcount_w24), .AD2(r_gcount_w25), .AD1(r_gcount_w26), 
        .AD0(scuba_vlo), .DO0(rcount_w4));

    defparam LUT4_10.initval =  16'h6996 ;
    ROM16X1A LUT4_10 (.AD3(r_gcount_w22), .AD2(r_gcount_w23), .AD1(r_gcount_w24), 
        .AD0(rcount_w5), .DO0(rcount_w2));

    defparam LUT4_9.initval =  16'h6996 ;
    ROM16X1A LUT4_9 (.AD3(r_gcount_w21), .AD2(r_gcount_w22), .AD1(r_gcount_w23), 
        .AD0(rcount_w4), .DO0(rcount_w1));

    defparam LUT4_8.initval =  16'h6996 ;
    ROM16X1A LUT4_8 (.AD3(r_gcount_w20), .AD2(r_gcount_w21), .AD1(r_gcount_w22), 
        .AD0(r_g2b_xor_cluster_0), .DO0(rcount_w0));

    defparam LUT4_7.initval =  16'h0410 ;
    ROM16X1A LUT4_7 (.AD3(rptr_6), .AD2(rcount_6), .AD1(w_gcount_r26), .AD0(scuba_vlo), 
        .DO0(empty_cmp_set));

    defparam LUT4_6.initval =  16'h1004 ;
    ROM16X1A LUT4_6 (.AD3(rptr_6), .AD2(rcount_6), .AD1(w_gcount_r26), .AD0(scuba_vlo), 
        .DO0(empty_cmp_clr));

    defparam LUT4_5.initval =  16'h0140 ;
    ROM16X1A LUT4_5 (.AD3(wptr_6), .AD2(wcount_6), .AD1(r_gcount_w26), .AD0(scuba_vlo), 
        .DO0(full_cmp_set));

    defparam LUT4_4.initval =  16'h4001 ;
    ROM16X1A LUT4_4 (.AD3(wptr_6), .AD2(wcount_6), .AD1(r_gcount_w26), .AD0(scuba_vlo), 
        .DO0(full_cmp_clr));

    defparam LUT4_3.initval =  16'h13c8 ;
    ROM16X1A LUT4_3 (.AD3(ae_setcount_6), .AD2(rcount_6), .AD1(w_gcount_r26), 
        .AD0(rptr_6), .DO0(ae_set_cmp_set));

    defparam LUT4_2.initval =  16'h2004 ;
    ROM16X1A LUT4_2 (.AD3(ae_setcount_6), .AD2(rcount_6), .AD1(w_gcount_r26), 
        .AD0(rptr_6), .DO0(ae_set_cmp_clr));

    defparam LUT4_1.initval =  16'h4c32 ;
    ROM16X1A LUT4_1 (.AD3(af_setcount_6), .AD2(wcount_6), .AD1(r_gcount_w26), 
        .AD0(wptr_6), .DO0(af_set_cmp_set));

    defparam LUT4_0.initval =  16'h8001 ;
    ROM16X1A LUT4_0 (.AD3(af_setcount_6), .AD2(wcount_6), .AD1(r_gcount_w26), 
        .AD0(wptr_6), .DO0(af_set_cmp_clr));

    FD1P3BX FF_95 (.D(iwcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(wcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_94 (.D(iwcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_93 (.D(iwcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_92 (.D(iwcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_91 (.D(iwcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_90 (.D(iwcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_89 (.D(iwcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_88 (.D(w_gdata_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_87 (.D(w_gdata_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_86 (.D(w_gdata_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_85 (.D(w_gdata_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_84 (.D(w_gdata_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_83 (.D(w_gdata_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_82 (.D(wcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(w_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_81 (.D(wcount_0), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_80 (.D(wcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_79 (.D(wcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_78 (.D(wcount_3), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_77 (.D(wcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_76 (.D(wcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_75 (.D(wcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(wptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_74 (.D(ircount_0), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(rcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_73 (.D(ircount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_72 (.D(ircount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_71 (.D(ircount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_70 (.D(ircount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_69 (.D(ircount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_68 (.D(ircount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(rcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_67 (.D(r_gdata_0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_66 (.D(r_gdata_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_65 (.D(r_gdata_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_64 (.D(r_gdata_3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_63 (.D(r_gdata_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_62 (.D(r_gdata_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(r_gcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_61 (.D(rcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(r_gcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_60 (.D(rcount_0), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_59 (.D(rcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_58 (.D(rcount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_57 (.D(rcount_3), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_56 (.D(rcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_55 (.D(rcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_54 (.D(rcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), .Q(rptr_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_53 (.D(rdataout0), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_52 (.D(rdataout1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_51 (.D(rdataout2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_50 (.D(rdataout3), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_49 (.D(rdataout4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_48 (.D(rdataout5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_47 (.D(rdataout6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_46 (.D(rdataout7), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(Q[7]))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_45 (.D(w_gcount_0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_44 (.D(w_gcount_1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_43 (.D(w_gcount_2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_42 (.D(w_gcount_3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_41 (.D(w_gcount_4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_40 (.D(w_gcount_5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_39 (.D(w_gcount_6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_38 (.D(r_gcount_0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w0))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_37 (.D(r_gcount_1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w1))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_36 (.D(r_gcount_2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w2))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_35 (.D(r_gcount_3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w3))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_34 (.D(r_gcount_4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w4))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_33 (.D(r_gcount_5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w5))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_32 (.D(r_gcount_6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_31 (.D(w_gcount_r0), .CK(RdClock), .CD(Reset), .Q(w_gcount_r20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_30 (.D(w_gcount_r1), .CK(RdClock), .CD(Reset), .Q(w_gcount_r21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_29 (.D(w_gcount_r2), .CK(RdClock), .CD(Reset), .Q(w_gcount_r22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_28 (.D(w_gcount_r3), .CK(RdClock), .CD(Reset), .Q(w_gcount_r23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_27 (.D(w_gcount_r4), .CK(RdClock), .CD(Reset), .Q(w_gcount_r24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_26 (.D(w_gcount_r5), .CK(RdClock), .CD(Reset), .Q(w_gcount_r25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_25 (.D(w_gcount_r6), .CK(RdClock), .CD(Reset), .Q(w_gcount_r26))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_24 (.D(r_gcount_w0), .CK(WrClock), .CD(rRst), .Q(r_gcount_w20))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_23 (.D(r_gcount_w1), .CK(WrClock), .CD(rRst), .Q(r_gcount_w21))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_22 (.D(r_gcount_w2), .CK(WrClock), .CD(rRst), .Q(r_gcount_w22))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_21 (.D(r_gcount_w3), .CK(WrClock), .CD(rRst), .Q(r_gcount_w23))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_20 (.D(r_gcount_w4), .CK(WrClock), .CD(rRst), .Q(r_gcount_w24))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_19 (.D(r_gcount_w5), .CK(WrClock), .CD(rRst), .Q(r_gcount_w25))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_18 (.D(r_gcount_w6), .CK(WrClock), .CD(rRst), .Q(r_gcount_w26))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_17 (.D(empty_d), .CK(RdClock), .PD(rRst), .Q(empty_i))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_16 (.D(full_d), .CK(WrClock), .CD(Reset), .Q(full_i))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_15 (.D(iae_setcount_0), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(ae_setcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(iae_setcount_1), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(iae_setcount_2), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_12 (.D(iae_setcount_3), .SP(rden_i), .CK(RdClock), .PD(rRst), 
        .Q(ae_setcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(iae_setcount_4), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(iae_setcount_5), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(iae_setcount_6), .SP(rden_i), .CK(RdClock), .CD(rRst), 
        .Q(ae_setcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1S3BX FF_8 (.D(ae_set_d), .CK(RdClock), .PD(rRst), .Q(AlmostEmpty))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_7 (.D(iaf_setcount_0), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(af_setcount_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(iaf_setcount_1), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(iaf_setcount_2), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_4 (.D(iaf_setcount_3), .SP(wren_i), .CK(WrClock), .PD(Reset), 
        .Q(af_setcount_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(iaf_setcount_4), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(iaf_setcount_5), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(iaf_setcount_6), .SP(wren_i), .CK(WrClock), .CD(Reset), 
        .Q(af_setcount_6))
             /* synthesis GSR="ENABLED" */;

    FD1S3DX FF_0 (.D(af_set), .CK(WrClock), .CD(Reset), .Q(AlmostFull))
             /* synthesis GSR="ENABLED" */;

    FADD2B w_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(w_gctr_ci), .S0(), .S1());

    CU2 w_gctr_0 (.CI(w_gctr_ci), .PC0(wcount_0), .PC1(wcount_1), .CO(co0), 
        .NC0(iwcount_0), .NC1(iwcount_1));

    CU2 w_gctr_1 (.CI(co0), .PC0(wcount_2), .PC1(wcount_3), .CO(co1), .NC0(iwcount_2), 
        .NC1(iwcount_3));

    CU2 w_gctr_2 (.CI(co1), .PC0(wcount_4), .PC1(wcount_5), .CO(co2), .NC0(iwcount_4), 
        .NC1(iwcount_5));

    CU2 w_gctr_3 (.CI(co2), .PC0(wcount_6), .PC1(scuba_vlo), .CO(co3), .NC0(iwcount_6), 
        .NC1());

    FADD2B r_gctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(r_gctr_ci), .S0(), .S1());

    CU2 r_gctr_0 (.CI(r_gctr_ci), .PC0(rcount_0), .PC1(rcount_1), .CO(co0_1), 
        .NC0(ircount_0), .NC1(ircount_1));

    CU2 r_gctr_1 (.CI(co0_1), .PC0(rcount_2), .PC1(rcount_3), .CO(co1_1), 
        .NC0(ircount_2), .NC1(ircount_3));

    CU2 r_gctr_2 (.CI(co1_1), .PC0(rcount_4), .PC1(rcount_5), .CO(co2_1), 
        .NC0(ircount_4), .NC1(ircount_5));

    CU2 r_gctr_3 (.CI(co2_1), .PC0(rcount_6), .PC1(scuba_vlo), .CO(co3_1), 
        .NC0(ircount_6), .NC1());

    MUX41 mux_7 (.D0(mdL0_0_7), .D1(mdL0_1_7), .D2(mdL0_2_7), .D3(mdL0_3_7), 
        .SD1(rptr_4), .SD2(rptr_5), .Z(rdataout7));

    MUX41 mux_6 (.D0(mdL0_0_6), .D1(mdL0_1_6), .D2(mdL0_2_6), .D3(mdL0_3_6), 
        .SD1(rptr_4), .SD2(rptr_5), .Z(rdataout6));

    MUX41 mux_5 (.D0(mdL0_0_5), .D1(mdL0_1_5), .D2(mdL0_2_5), .D3(mdL0_3_5), 
        .SD1(rptr_4), .SD2(rptr_5), .Z(rdataout5));

    MUX41 mux_4 (.D0(mdL0_0_4), .D1(mdL0_1_4), .D2(mdL0_2_4), .D3(mdL0_3_4), 
        .SD1(rptr_4), .SD2(rptr_5), .Z(rdataout4));

    MUX41 mux_3 (.D0(mdL0_0_3), .D1(mdL0_1_3), .D2(mdL0_2_3), .D3(mdL0_3_3), 
        .SD1(rptr_4), .SD2(rptr_5), .Z(rdataout3));

    MUX41 mux_2 (.D0(mdL0_0_2), .D1(mdL0_1_2), .D2(mdL0_2_2), .D3(mdL0_3_2), 
        .SD1(rptr_4), .SD2(rptr_5), .Z(rdataout2));

    MUX41 mux_1 (.D0(mdL0_0_1), .D1(mdL0_1_1), .D2(mdL0_2_1), .D3(mdL0_3_1), 
        .SD1(rptr_4), .SD2(rptr_5), .Z(rdataout1));

    MUX41 mux_0 (.D0(mdL0_0_0), .D1(mdL0_1_0), .D2(mdL0_2_0), .D3(mdL0_3_0), 
        .SD1(rptr_4), .SD2(rptr_5), .Z(rdataout0));

    FADD2B empty_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), 
        .B1(rden_i), .CI(scuba_vlo), .COUT(cmp_ci), .S0(), .S1());

    AGEB2 empty_cmp_0 (.A0(rcount_0), .A1(rcount_1), .B0(wcount_r0), .B1(wcount_r1), 
        .CI(cmp_ci), .GE(co0_2));

    AGEB2 empty_cmp_1 (.A0(rcount_2), .A1(rcount_3), .B0(wcount_r2), .B1(w_g2b_xor_cluster_0), 
        .CI(co0_2), .GE(co1_2));

    AGEB2 empty_cmp_2 (.A0(rcount_4), .A1(rcount_5), .B0(wcount_r4), .B1(wcount_r5), 
        .CI(co1_2), .GE(co2_2));

    AGEB2 empty_cmp_3 (.A0(empty_cmp_set), .A1(scuba_vlo), .B0(empty_cmp_clr), 
        .B1(scuba_vlo), .CI(co2_2), .GE(empty_d_c));

    FADD2B a0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(empty_d_c), .COUT(), .S0(empty_d), .S1());

    FADD2B full_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), .B1(wren_i), 
        .CI(scuba_vlo), .COUT(cmp_ci_1), .S0(), .S1());

    AGEB2 full_cmp_0 (.A0(wcount_0), .A1(wcount_1), .B0(rcount_w0), .B1(rcount_w1), 
        .CI(cmp_ci_1), .GE(co0_3));

    AGEB2 full_cmp_1 (.A0(wcount_2), .A1(wcount_3), .B0(rcount_w2), .B1(r_g2b_xor_cluster_0), 
        .CI(co0_3), .GE(co1_3));

    AGEB2 full_cmp_2 (.A0(wcount_4), .A1(wcount_5), .B0(rcount_w4), .B1(rcount_w5), 
        .CI(co1_3), .GE(co2_3));

    AGEB2 full_cmp_3 (.A0(full_cmp_set), .A1(scuba_vlo), .B0(full_cmp_clr), 
        .B1(scuba_vlo), .CI(co2_3), .GE(full_d_c));

    FADD2B a1 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(full_d_c), .COUT(), .S0(full_d), .S1());

    FADD2B ae_set_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), 
        .B1(scuba_vhi), .CI(scuba_vlo), .COUT(ae_set_ctr_ci), .S0(), .S1());

    CU2 ae_set_ctr_0 (.CI(ae_set_ctr_ci), .PC0(ae_setcount_0), .PC1(ae_setcount_1), 
        .CO(co0_4), .NC0(iae_setcount_0), .NC1(iae_setcount_1));

    CU2 ae_set_ctr_1 (.CI(co0_4), .PC0(ae_setcount_2), .PC1(ae_setcount_3), 
        .CO(co1_4), .NC0(iae_setcount_2), .NC1(iae_setcount_3));

    CU2 ae_set_ctr_2 (.CI(co1_4), .PC0(ae_setcount_4), .PC1(ae_setcount_5), 
        .CO(co2_4), .NC0(iae_setcount_4), .NC1(iae_setcount_5));

    CU2 ae_set_ctr_3 (.CI(co2_4), .PC0(ae_setcount_6), .PC1(scuba_vlo), 
        .CO(co3_2), .NC0(iae_setcount_6), .NC1());

    FADD2B ae_set_cmp_ci_a (.A0(scuba_vlo), .A1(rden_i), .B0(scuba_vlo), 
        .B1(rden_i), .CI(scuba_vlo), .COUT(cmp_ci_2), .S0(), .S1());

    AGEB2 ae_set_cmp_0 (.A0(ae_setcount_0), .A1(ae_setcount_1), .B0(wcount_r0), 
        .B1(wcount_r1), .CI(cmp_ci_2), .GE(co0_5));

    AGEB2 ae_set_cmp_1 (.A0(ae_setcount_2), .A1(ae_setcount_3), .B0(wcount_r2), 
        .B1(w_g2b_xor_cluster_0), .CI(co0_5), .GE(co1_5));

    AGEB2 ae_set_cmp_2 (.A0(ae_setcount_4), .A1(ae_setcount_5), .B0(wcount_r4), 
        .B1(wcount_r5), .CI(co1_5), .GE(co2_5));

    AGEB2 ae_set_cmp_3 (.A0(ae_set_cmp_set), .A1(scuba_vlo), .B0(ae_set_cmp_clr), 
        .B1(scuba_vlo), .CI(co2_5), .GE(ae_set_d_c));

    FADD2B a2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(ae_set_d_c), .COUT(), .S0(ae_set_d), .S1());

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B af_set_ctr_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), 
        .B1(scuba_vhi), .CI(scuba_vlo), .COUT(af_set_ctr_ci), .S0(), .S1());

    CU2 af_set_ctr_0 (.CI(af_set_ctr_ci), .PC0(af_setcount_0), .PC1(af_setcount_1), 
        .CO(co0_6), .NC0(iaf_setcount_0), .NC1(iaf_setcount_1));

    CU2 af_set_ctr_1 (.CI(co0_6), .PC0(af_setcount_2), .PC1(af_setcount_3), 
        .CO(co1_6), .NC0(iaf_setcount_2), .NC1(iaf_setcount_3));

    CU2 af_set_ctr_2 (.CI(co1_6), .PC0(af_setcount_4), .PC1(af_setcount_5), 
        .CO(co2_6), .NC0(iaf_setcount_4), .NC1(iaf_setcount_5));

    CU2 af_set_ctr_3 (.CI(co2_6), .PC0(af_setcount_6), .PC1(scuba_vlo), 
        .CO(co3_3), .NC0(iaf_setcount_6), .NC1());

    FADD2B af_set_cmp_ci_a (.A0(scuba_vlo), .A1(wren_i), .B0(scuba_vlo), 
        .B1(wren_i), .CI(scuba_vlo), .COUT(cmp_ci_3), .S0(), .S1());

    AGEB2 af_set_cmp_0 (.A0(af_setcount_0), .A1(af_setcount_1), .B0(rcount_w0), 
        .B1(rcount_w1), .CI(cmp_ci_3), .GE(co0_7));

    AGEB2 af_set_cmp_1 (.A0(af_setcount_2), .A1(af_setcount_3), .B0(rcount_w2), 
        .B1(r_g2b_xor_cluster_0), .CI(co0_7), .GE(co1_7));

    AGEB2 af_set_cmp_2 (.A0(af_setcount_4), .A1(af_setcount_5), .B0(rcount_w4), 
        .B1(rcount_w5), .CI(co1_7), .GE(co2_7));

    AGEB2 af_set_cmp_3 (.A0(af_set_cmp_set), .A1(scuba_vlo), .B0(af_set_cmp_clr), 
        .B1(scuba_vlo), .CI(co2_7), .GE(af_set_c));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FADD2B a3 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(af_set_c), .COUT(), .S0(af_set), .S1());

    defparam fifo_pfu_0_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_0_0 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_0_4), .DO1(mdL0_0_5), .DO2(mdL0_0_6), .DO3(mdL0_0_7))
             /* synthesis MEM_INIT_FILE="(0-15)(0-3)" */
             /* synthesis MEM_LPC_FILE="serialFIFO.lpc" */
             /* synthesis COMP="fifo_pfu_0_0" */;

    defparam fifo_pfu_0_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_0_1 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec0_wre3), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_0_0), .DO1(mdL0_0_1), .DO2(mdL0_0_2), .DO3(mdL0_0_3))
             /* synthesis MEM_INIT_FILE="(0-15)(4-7)" */
             /* synthesis MEM_LPC_FILE="serialFIFO.lpc" */
             /* synthesis COMP="fifo_pfu_0_1" */;

    defparam fifo_pfu_1_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_1_0 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec1_wre7), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_1_4), .DO1(mdL0_1_5), .DO2(mdL0_1_6), .DO3(mdL0_1_7))
             /* synthesis MEM_INIT_FILE="(16-31)(0-3)" */
             /* synthesis MEM_LPC_FILE="serialFIFO.lpc" */
             /* synthesis COMP="fifo_pfu_1_0" */;

    defparam fifo_pfu_1_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_1_1 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec1_wre7), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_1_0), .DO1(mdL0_1_1), .DO2(mdL0_1_2), .DO3(mdL0_1_3))
             /* synthesis MEM_INIT_FILE="(16-31)(4-7)" */
             /* synthesis MEM_LPC_FILE="serialFIFO.lpc" */
             /* synthesis COMP="fifo_pfu_1_1" */;

    defparam fifo_pfu_2_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_2_0 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec2_wre11), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_2_4), .DO1(mdL0_2_5), .DO2(mdL0_2_6), .DO3(mdL0_2_7))
             /* synthesis MEM_INIT_FILE="(32-47)(0-3)" */
             /* synthesis MEM_LPC_FILE="serialFIFO.lpc" */
             /* synthesis COMP="fifo_pfu_2_0" */;

    defparam fifo_pfu_2_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_2_1 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec2_wre11), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_2_0), .DO1(mdL0_2_1), .DO2(mdL0_2_2), .DO3(mdL0_2_3))
             /* synthesis MEM_INIT_FILE="(32-47)(4-7)" */
             /* synthesis MEM_LPC_FILE="serialFIFO.lpc" */
             /* synthesis COMP="fifo_pfu_2_1" */;

    defparam fifo_pfu_3_0.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_3_0 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), 
        .DI3(Data[7]), .WCK(WrClock), .WRE(dec3_wre15), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_3_4), .DO1(mdL0_3_5), .DO2(mdL0_3_6), .DO3(mdL0_3_7))
             /* synthesis MEM_INIT_FILE="(48-63)(0-3)" */
             /* synthesis MEM_LPC_FILE="serialFIFO.lpc" */
             /* synthesis COMP="fifo_pfu_3_0" */;

    defparam fifo_pfu_3_1.initval = "0x0000000000000000" ;
    DPR16X4C fifo_pfu_3_1 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), 
        .DI3(Data[3]), .WCK(WrClock), .WRE(dec3_wre15), .RAD0(rptr_0), .RAD1(rptr_1), 
        .RAD2(rptr_2), .RAD3(rptr_3), .WAD0(wptr_0), .WAD1(wptr_1), .WAD2(wptr_2), 
        .WAD3(wptr_3), .DO0(mdL0_3_0), .DO1(mdL0_3_1), .DO2(mdL0_3_2), .DO3(mdL0_3_3))
             /* synthesis MEM_INIT_FILE="(48-63)(4-7)" */
             /* synthesis MEM_LPC_FILE="serialFIFO.lpc" */
             /* synthesis COMP="fifo_pfu_3_1" */;

    assign Empty = empty_i;
    assign Full = full_i;


    // exemplar begin
    // exemplar attribute FF_95 GSR ENABLED
    // exemplar attribute FF_94 GSR ENABLED
    // exemplar attribute FF_93 GSR ENABLED
    // exemplar attribute FF_92 GSR ENABLED
    // exemplar attribute FF_91 GSR ENABLED
    // exemplar attribute FF_90 GSR ENABLED
    // exemplar attribute FF_89 GSR ENABLED
    // exemplar attribute FF_88 GSR ENABLED
    // exemplar attribute FF_87 GSR ENABLED
    // exemplar attribute FF_86 GSR ENABLED
    // exemplar attribute FF_85 GSR ENABLED
    // exemplar attribute FF_84 GSR ENABLED
    // exemplar attribute FF_83 GSR ENABLED
    // exemplar attribute FF_82 GSR ENABLED
    // exemplar attribute FF_81 GSR ENABLED
    // exemplar attribute FF_80 GSR ENABLED
    // exemplar attribute FF_79 GSR ENABLED
    // exemplar attribute FF_78 GSR ENABLED
    // exemplar attribute FF_77 GSR ENABLED
    // exemplar attribute FF_76 GSR ENABLED
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute fifo_pfu_0_0 MEM_INIT_FILE (0-15)(0-3)
    // exemplar attribute fifo_pfu_0_0 MEM_LPC_FILE serialFIFO.lpc
    // exemplar attribute fifo_pfu_0_0 COMP fifo_pfu_0_0
    // exemplar attribute fifo_pfu_0_1 MEM_INIT_FILE (0-15)(4-7)
    // exemplar attribute fifo_pfu_0_1 MEM_LPC_FILE serialFIFO.lpc
    // exemplar attribute fifo_pfu_0_1 COMP fifo_pfu_0_1
    // exemplar attribute fifo_pfu_1_0 MEM_INIT_FILE (16-31)(0-3)
    // exemplar attribute fifo_pfu_1_0 MEM_LPC_FILE serialFIFO.lpc
    // exemplar attribute fifo_pfu_1_0 COMP fifo_pfu_1_0
    // exemplar attribute fifo_pfu_1_1 MEM_INIT_FILE (16-31)(4-7)
    // exemplar attribute fifo_pfu_1_1 MEM_LPC_FILE serialFIFO.lpc
    // exemplar attribute fifo_pfu_1_1 COMP fifo_pfu_1_1
    // exemplar attribute fifo_pfu_2_0 MEM_INIT_FILE (32-47)(0-3)
    // exemplar attribute fifo_pfu_2_0 MEM_LPC_FILE serialFIFO.lpc
    // exemplar attribute fifo_pfu_2_0 COMP fifo_pfu_2_0
    // exemplar attribute fifo_pfu_2_1 MEM_INIT_FILE (32-47)(4-7)
    // exemplar attribute fifo_pfu_2_1 MEM_LPC_FILE serialFIFO.lpc
    // exemplar attribute fifo_pfu_2_1 COMP fifo_pfu_2_1
    // exemplar attribute fifo_pfu_3_0 MEM_INIT_FILE (48-63)(0-3)
    // exemplar attribute fifo_pfu_3_0 MEM_LPC_FILE serialFIFO.lpc
    // exemplar attribute fifo_pfu_3_0 COMP fifo_pfu_3_0
    // exemplar attribute fifo_pfu_3_1 MEM_INIT_FILE (48-63)(4-7)
    // exemplar attribute fifo_pfu_3_1 MEM_LPC_FILE serialFIFO.lpc
    // exemplar attribute fifo_pfu_3_1 COMP fifo_pfu_3_1
    // exemplar end

endmodule
